"""Endpoint catalog for Literary Studio API coverage tests."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Optional


class AuthLevel(str, Enum):
    PUBLIC = "public"
    AUTH = "auth"
    ADMIN = "admin"
    PROJECT_READ = "project_read"
    PROJECT_WRITE = "project_write"
    PROJECT_MANAGE = "project_manage"
    SCREENPLAY = "screenplay_read"  # read on screenplay project
    SCREENPLAY_WRITE = "screenplay_write"


@dataclass(frozen=True)
class EndpointSpec:
    module: str
    name: str
    method: str
    path: str
    auth: AuthLevel
    json_body: Optional[dict[str, Any] | list] = None
    query: Optional[dict[str, Any]] = None
    positive_status: tuple[int, ...] = (200,)
    skip_auth_negative: bool = False
    notes: str = ""


def _pid(key: str = "project_id") -> str:
    return "{" + key + "}"


_ALL_ENDPOINTS_RAW: list[EndpointSpec] = [
    # ── Health & System ──
    EndpointSpec("health", "health", "GET", "/health", AuthLevel.PUBLIC, positive_status=(200,)),
    EndpointSpec("health", "usage", "GET", "/usage", AuthLevel.AUTH),
    EndpointSpec("health", "upload_formats", "GET", "/upload/formats", AuthLevel.AUTH),
    EndpointSpec("health", "export_formats", "GET", "/export/formats", AuthLevel.AUTH),
    EndpointSpec("health", "project_usage", "GET", f"/projects/{_pid()}/usage", AuthLevel.PROJECT_READ),
    EndpointSpec("health", "jobs_status", "GET", "/jobs/{job_id}", AuthLevel.AUTH, positive_status=(200, 404)),

    # ── Auth ──
    EndpointSpec("auth", "login", "POST", "/auth/login", AuthLevel.PUBLIC,
                 json_body={"username": "admin", "password": "admin123"}, positive_status=(200,)),
    EndpointSpec("auth", "register", "POST", "/auth/register", AuthLevel.PUBLIC,
                 json_body={"username": "x", "password": "123456"}, positive_status=(201, 403)),
    EndpointSpec("auth", "me", "GET", "/auth/me", AuthLevel.AUTH),
    EndpointSpec("auth", "list_users", "GET", "/auth/users", AuthLevel.ADMIN),
    EndpointSpec("auth", "create_user", "POST", "/auth/users", AuthLevel.ADMIN,
                 json_body={"username": "tmp", "password": "123456"}, positive_status=(201, 400)),
    EndpointSpec("auth", "update_user", "PATCH", "/auth/users/{user_id}", AuthLevel.ADMIN,
                 json_body={"display_name": "test"}, positive_status=(200, 400, 404)),
    EndpointSpec("auth", "delete_user", "DELETE", "/auth/users/{user_id}", AuthLevel.ADMIN,
                 positive_status=(200, 400, 404)),

    # ── Models & Settings ──
    EndpointSpec("models", "list", "GET", "/models", AuthLevel.AUTH),
    EndpointSpec("models", "create", "POST", "/models", AuthLevel.AUTH,
                 json_body={"name": "test", "provider": "openai", "model": "gpt-4o-mini", "base_url": "https://api.openai.com/v1"},
                 positive_status=(200, 201, 400)),
    EndpointSpec("models", "update", "PUT", "/models/{model_id}", AuthLevel.AUTH,
                 json_body={"name": "patched"}, positive_status=(200, 404)),
    EndpointSpec("models", "delete", "DELETE", "/models/{model_id}", AuthLevel.AUTH, positive_status=(200, 404)),
    EndpointSpec("models", "activate", "POST", "/models/{model_id}/activate", AuthLevel.AUTH, positive_status=(200, 404)),
    EndpointSpec("models", "import_cc_switch", "GET", "/models/import/cc-switch", AuthLevel.AUTH, positive_status=(200, 400)),
    EndpointSpec("models", "test_connection", "POST", "/models/test", AuthLevel.AUTH,
                 json_body={"base_url": "https://example.invalid", "model": "test"}, positive_status=(200, 400, 502)),
    EndpointSpec("models", "test_by_id", "POST", "/models/{model_id}/test", AuthLevel.AUTH,
                 positive_status=(200, 400, 404)),
    EndpointSpec("models", "settings_get", "GET", "/settings", AuthLevel.AUTH),
    EndpointSpec("models", "settings_put", "PUT", "/settings", AuthLevel.AUTH,
                 json_body={"provider": "openai", "model": "gpt-4o-mini"}, positive_status=(200, 400)),

    # ── Projects Core ──
    EndpointSpec("projects", "list", "GET", "/projects", AuthLevel.AUTH),
    EndpointSpec("projects", "create", "POST", "/projects", AuthLevel.AUTH,
                 json_body={"title": "catalog-test"}, positive_status=(200,)),
    EndpointSpec("projects", "get", "GET", f"/projects/{_pid()}", AuthLevel.PROJECT_READ),
    EndpointSpec("projects", "patch", "PATCH", f"/projects/{_pid()}", AuthLevel.PROJECT_WRITE,
                 json_body={"summary": "updated"}, positive_status=(200,)),
    EndpointSpec("projects", "delete", "DELETE", f"/projects/{_pid()}", AuthLevel.PROJECT_MANAGE,
                 positive_status=(200,)),
    EndpointSpec("projects", "shares_get", "GET", f"/projects/{_pid()}/shares", AuthLevel.PROJECT_MANAGE),
    EndpointSpec("projects", "shares_put", "PUT", f"/projects/{_pid()}/shares", AuthLevel.PROJECT_MANAGE,
                 json_body={"shares": []}),
    EndpointSpec("projects", "takeover", "GET", f"/projects/{_pid()}/takeover", AuthLevel.PROJECT_READ),
    EndpointSpec("projects", "search", "GET", f"/projects/{_pid()}/search", AuthLevel.PROJECT_READ,
                 query={"q": "测试"}, positive_status=(200, 400)),
    EndpointSpec("projects", "write_redirect", "POST", f"/projects/{_pid()}/write", AuthLevel.PROJECT_READ,
                 positive_status=(400,)),

    # ── Chapters & Files ──
    EndpointSpec("chapters", "list", "GET", f"/projects/{_pid()}/chapters", AuthLevel.PROJECT_READ),
    EndpointSpec("chapters", "get", "GET", f"/projects/{_pid()}/chapters/{{chapter}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("chapters", "put", "PUT", f"/projects/{_pid()}/chapters/{{chapter}}", AuthLevel.PROJECT_WRITE,
                 json_body={"content": "# test\n"}, positive_status=(200, 404)),
    EndpointSpec("chapters", "delete", "DELETE", f"/projects/{_pid()}/chapters/{{chapter}}", AuthLevel.PROJECT_WRITE,
                 positive_status=(200, 404)),
    EndpointSpec("chapters", "manuscripts", "POST", f"/projects/{_pid()}/manuscripts", AuthLevel.PROJECT_WRITE,
                 json_body={"title": "章", "content": "内容"}),
    EndpointSpec("chapters", "files_list", "GET", f"/projects/{_pid()}/files/manuscript", AuthLevel.PROJECT_READ),
    EndpointSpec("chapters", "files_get", "GET", f"/projects/{_pid()}/files/manuscript/{{chapter}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("chapters", "files_put", "PUT", f"/projects/{_pid()}/files/manuscript/{{chapter}}", AuthLevel.PROJECT_WRITE,
                 json_body={"content": "x"}, positive_status=(200, 404)),
    EndpointSpec("chapters", "export_chapter", "GET", f"/projects/{_pid()}/chapters/{{chapter}}/export",
                 AuthLevel.PROJECT_READ, query={"format": "md"}, positive_status=(200, 404)),
    EndpointSpec("chapters", "download", "GET", f"/projects/{_pid()}/download", AuthLevel.PROJECT_READ,
                 query={"format": "zip"}, positive_status=(200, 400, 500)),

    # ── Chat & Sessions ──
    EndpointSpec("chat", "get", "GET", f"/projects/{_pid()}/chat", AuthLevel.PROJECT_READ),
    EndpointSpec("chat", "post", "POST", f"/projects/{_pid()}/chat", AuthLevel.PROJECT_WRITE,
                 json_body={"message": "hello"}, positive_status=(200, 400, 502)),
    EndpointSpec("chat", "clear", "DELETE", f"/projects/{_pid()}/chat", AuthLevel.PROJECT_WRITE),
    EndpointSpec("chat", "sessions_list", "GET", f"/projects/{_pid()}/sessions", AuthLevel.PROJECT_READ),
    EndpointSpec("chat", "sessions_create", "POST", f"/projects/{_pid()}/sessions", AuthLevel.PROJECT_WRITE,
                 json_body={"title": "s1"}),
    EndpointSpec("chat", "sessions_focus", "POST", f"/projects/{_pid()}/sessions/focus", AuthLevel.PROJECT_WRITE,
                 json_body={"scope": "project"}),
    EndpointSpec("chat", "sessions_get", "GET", f"/projects/{_pid()}/sessions/{{session_id}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("chat", "sessions_patch", "PATCH", f"/projects/{_pid()}/sessions/{{session_id}}", AuthLevel.PROJECT_WRITE,
                 json_body={"title": "renamed"}, positive_status=(200, 404)),
    EndpointSpec("chat", "sessions_memory", "GET", f"/projects/{_pid()}/sessions/{{session_id}}/memory",
                 AuthLevel.PROJECT_READ, positive_status=(200, 404)),
    EndpointSpec("chat", "sessions_delete", "DELETE", f"/projects/{_pid()}/sessions/{{session_id}}",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 404)),
    EndpointSpec("chat", "sessions_clear_msgs", "DELETE", f"/projects/{_pid()}/sessions/{{session_id}}/messages",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 404)),

    # ── Tools & Skills ──
    EndpointSpec("tools", "overview", "GET", "/tools/overview", AuthLevel.AUTH),
    EndpointSpec("tools", "skills", "GET", "/tools/skills", AuthLevel.AUTH),
    EndpointSpec("tools", "skills_search", "GET", "/tools/skills/search", AuthLevel.AUTH, query={"q": "writer"}),
    EndpointSpec("tools", "skills_install", "POST", "/tools/skills/install", AuthLevel.ADMIN,
                 json_body={"source": "invalid"}, positive_status=(200, 400, 404)),
    EndpointSpec("tools", "catalogue_update", "POST", "/tools/skills/catalogue/update", AuthLevel.ADMIN,
                 positive_status=(200, 400, 500)),
    EndpointSpec("tools", "literary_writer", "PUT", "/tools/literary-writer", AuthLevel.AUTH,
                 json_body={"path": "."}, positive_status=(200, 400)),
    EndpointSpec("tools", "default_skill_put", "PUT", "/tools/default-skill", AuthLevel.AUTH,
                 json_body={"skill_id": "literary-writer"}, positive_status=(200, 400)),
    EndpointSpec("tools", "default_skill_get", "GET", "/tools/default-skill", AuthLevel.AUTH),
    EndpointSpec("tools", "capabilities_default", "GET", "/tools/skills/capabilities/default", AuthLevel.AUTH),
    EndpointSpec("tools", "capabilities", "GET", "/tools/skills/{skill_id}/capabilities", AuthLevel.AUTH,
                 positive_status=(200, 404)),
    EndpointSpec("tools", "invoke", "POST", "/tools/skills/invoke", AuthLevel.AUTH,
                 json_body={"command": "help"}, positive_status=(200, 400, 404, 500)),
    EndpointSpec("tools", "project_invoke", "POST", f"/projects/{_pid()}/skill/invoke", AuthLevel.PROJECT_WRITE,
                 json_body={"command": "help"}, positive_status=(200, 400, 404, 500)),
    EndpointSpec("tools", "preflight", "GET", f"/projects/{_pid()}/skill/preflight", AuthLevel.PROJECT_READ),

    # ── MCP ──
    EndpointSpec("mcp", "overview", "GET", "/mcp/overview", AuthLevel.AUTH),
    EndpointSpec("mcp", "servers", "GET", "/mcp/servers", AuthLevel.AUTH),
    EndpointSpec("mcp", "server_enabled", "PUT", "/mcp/servers/{server_id}/enabled", AuthLevel.AUTH,
                 json_body={"enabled": False}, positive_status=(200, 404)),
    EndpointSpec("mcp", "server_tools", "GET", "/mcp/servers/{server_id}/tools", AuthLevel.AUTH,
                 positive_status=(200, 400, 404, 502)),
    EndpointSpec("mcp", "call", "POST", "/mcp/call", AuthLevel.AUTH,
                 json_body={"server_id": "x", "tool": "y"}, positive_status=(200, 400, 404, 502)),
    EndpointSpec("mcp", "health", "POST", "/mcp/health", AuthLevel.AUTH, json_body={}, positive_status=(200, 400)),
    EndpointSpec("mcp", "studio_get", "GET", "/mcp/studio", AuthLevel.AUTH),
    EndpointSpec("mcp", "studio_put", "PUT", "/mcp/studio", AuthLevel.AUTH,
                 json_body={"content": "{}"}, positive_status=(200, 400)),
    EndpointSpec("mcp", "runtime_refresh", "POST", "/mcp/runtime/refresh", AuthLevel.AUTH),
    EndpointSpec("mcp", "registry_search", "GET", "/mcp/registry/search", AuthLevel.AUTH, query={"q": "test"}),
    EndpointSpec("mcp", "registry_meta", "GET", "/mcp/registry/meta", AuthLevel.AUTH),
    EndpointSpec("mcp", "registry_install", "POST", "/mcp/registry/install", AuthLevel.AUTH,
                 json_body={"id": "invalid"}, positive_status=(200, 400, 404)),

    # ── Creative Center (/api/studio) ──
    EndpointSpec("studio", "overview", "GET", "/studio/overview", AuthLevel.AUTH),
    EndpointSpec("studio", "dashboard", "GET", "/studio/dashboard", AuthLevel.AUTH,
                 notes="deprecated alias of overview"),
    EndpointSpec("studio", "assets_list", "GET", "/studio/assets", AuthLevel.AUTH,
                 query={"project_id": "{project_id}"}, positive_status=(200, 400)),
    EndpointSpec("studio", "assets_create", "POST", "/studio/assets", AuthLevel.AUTH,
                 json_body={"project_id": "{project_id}", "type": "note", "title": "t"},
                 positive_status=(410,)),
    EndpointSpec("studio", "assets_delete", "DELETE", "/studio/assets/{asset_id}", AuthLevel.AUTH,
                 query={"project_id": "{project_id}"}, positive_status=(410, 404, 500)),
    EndpointSpec("studio", "assets_update", "PUT", "/studio/assets/{asset_id}", AuthLevel.AUTH,
                 json_body={"project_id": "{project_id}", "title": "x"}, positive_status=(410, 404)),

    # ── Versions ──
    EndpointSpec("versions", "list", "GET", f"/projects/{_pid()}/versions", AuthLevel.PROJECT_READ),
    EndpointSpec("versions", "create", "POST", f"/projects/{_pid()}/versions/create", AuthLevel.PROJECT_WRITE,
                 json_body={"label": "v1"}),
    EndpointSpec("versions", "get", "GET", f"/projects/{_pid()}/versions/{{version_id}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("versions", "diff", "GET", f"/projects/{_pid()}/versions/{{version_id}}/diff", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("versions", "restore", "POST", f"/projects/{_pid()}/versions/{{version_id}}/restore",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 404)),
    EndpointSpec("versions", "delete", "DELETE", f"/projects/{_pid()}/versions/{{version_id}}",
                 AuthLevel.PROJECT_MANAGE, positive_status=(200, 404)),

    # ── Measurement ──
    EndpointSpec("measurement", "review", "GET", f"/projects/{_pid()}/measurement/review", AuthLevel.PROJECT_READ),
    EndpointSpec("measurement", "review_run", "POST", f"/projects/{_pid()}/measurement/review/run",
                 AuthLevel.PROJECT_WRITE),
    EndpointSpec("measurement", "health", "GET", f"/projects/{_pid()}/measurement/health", AuthLevel.PROJECT_READ),

    # ── Story OS ──
    EndpointSpec("story", "knowledge", "GET", f"/projects/{_pid()}/story/knowledge", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "knowledge_put", "PUT", f"/projects/{_pid()}/story/knowledge", AuthLevel.PROJECT_WRITE,
                 json_body={"story_summary": {"logline": "pytest", "themes": []}},
                 positive_status=(200, 400)),
    EndpointSpec("story", "knowledge_rebuild", "POST", f"/projects/{_pid()}/story/knowledge/rebuild",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400)),
    EndpointSpec("story", "summaries", "GET", f"/projects/{_pid()}/story/summaries", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "summaries_rebuild", "POST", f"/projects/{_pid()}/story/summaries/rebuild",
                 AuthLevel.PROJECT_WRITE),
    EndpointSpec("story", "index_query", "GET", f"/projects/{_pid()}/story/index/query", AuthLevel.PROJECT_READ,
                 query={"q": "主角"}),
    EndpointSpec("story", "index_character", "GET", f"/projects/{_pid()}/story/index/character", AuthLevel.PROJECT_READ,
                 query={"q": "主角"}),
    EndpointSpec("story", "index_relationship", "GET", f"/projects/{_pid()}/story/index/relationship",
                 AuthLevel.PROJECT_READ, query={"q": "关系"}),
    EndpointSpec("story", "index_timeline", "GET", f"/projects/{_pid()}/story/index/timeline", AuthLevel.PROJECT_READ,
                 query={"q": "时间"}),
    EndpointSpec("story", "index_foreshadow", "GET", f"/projects/{_pid()}/story/index/foreshadow", AuthLevel.PROJECT_READ,
                 query={"q": "伏笔"}),
    EndpointSpec("story", "index_location", "GET", f"/projects/{_pid()}/story/index/location", AuthLevel.PROJECT_READ,
                 query={"q": "地点"}),
    EndpointSpec("story", "route", "POST", f"/projects/{_pid()}/story/route", AuthLevel.PROJECT_WRITE,
                 json_body={"message": "写下一章"}, positive_status=(200, 400)),
    EndpointSpec("story", "plans", "GET", f"/projects/{_pid()}/story/plans", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "plan_get", "GET", f"/projects/{_pid()}/story/plans/{{plan_id}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("story", "plans_diff", "POST", f"/projects/{_pid()}/story/plans/diff", AuthLevel.PROJECT_WRITE,
                 json_body={"message": "改大纲"}),
    EndpointSpec("story", "plans_rewrite", "POST", f"/projects/{_pid()}/story/plans/rewrite", AuthLevel.PROJECT_WRITE,
                 json_body={"message": "重写"}),
    EndpointSpec("story", "plan_confirm", "POST", f"/projects/{_pid()}/story/plans/{{plan_id}}/confirm",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404)),
    EndpointSpec("story", "plan_complete", "POST", f"/projects/{_pid()}/story/plans/{{plan_id}}/complete",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404)),
    EndpointSpec("story", "health", "GET", f"/projects/{_pid()}/story/health", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "consistency", "GET", f"/projects/{_pid()}/story/consistency", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "verify", "GET", f"/projects/{_pid()}/story/verify", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "verify_run", "POST", f"/projects/{_pid()}/story/verify/run", AuthLevel.PROJECT_WRITE,
                 json_body={"chapter": 1}, positive_status=(200, 400)),
    EndpointSpec("story", "health_review", "POST", f"/projects/{_pid()}/story/health/review", AuthLevel.PROJECT_WRITE,
                 json_body={"filename": "x.md"}, positive_status=(200, 400, 404)),
    EndpointSpec("story", "understanding", "GET", f"/projects/{_pid()}/story/understanding", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "actions_today", "GET", f"/projects/{_pid()}/story/actions/today", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "action_plan", "POST", f"/projects/{_pid()}/story/actions/{{action_id}}/plan",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404)),
    EndpointSpec("story", "sync", "POST", f"/projects/{_pid()}/story/sync", AuthLevel.PROJECT_WRITE,
                 json_body={"mode": "quick"}, positive_status=(200, 400)),
    EndpointSpec("story", "planner_generate", "POST", f"/projects/{_pid()}/story/planner/generate",
                 AuthLevel.PROJECT_WRITE, json_body={"horizon": 7}),
    EndpointSpec("story", "planner_bundle", "GET", f"/projects/{_pid()}/story/planner/bundle", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "planner_goal", "GET", f"/projects/{_pid()}/story/planner/goal", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "planner_roadmap", "GET", f"/projects/{_pid()}/story/planner/roadmap", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "planner_preferences_get", "GET", f"/projects/{_pid()}/story/planner/preferences",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("story", "planner_preferences_put", "PUT", f"/projects/{_pid()}/story/planner/preferences",
                 AuthLevel.PROJECT_WRITE, json_body={"daily_word_goal": 2000}),
    EndpointSpec("story", "tasks_today", "GET", f"/projects/{_pid()}/story/tasks/today", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "tasks", "GET", f"/projects/{_pid()}/story/tasks", AuthLevel.PROJECT_READ),
    EndpointSpec("story", "tasks_rebuild", "POST", f"/projects/{_pid()}/story/tasks/rebuild", AuthLevel.PROJECT_WRITE,
                 json_body={"horizon": 7}),
    EndpointSpec("story", "task_plan", "POST", f"/projects/{_pid()}/story/tasks/{{task_id}}/plan",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404, 500)),
    EndpointSpec("story", "task_start", "POST", f"/projects/{_pid()}/story/tasks/{{task_id}}/start",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404)),
    EndpointSpec("story", "tasks_next", "POST", f"/projects/{_pid()}/story/tasks/next", AuthLevel.PROJECT_WRITE,
                 positive_status=(200, 404)),
    EndpointSpec("story", "task_complete", "POST", f"/projects/{_pid()}/story/tasks/{{task_id}}/complete",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400, 404)),

    # ── Story Engine ──
    EndpointSpec("engine", "canon_list", "GET", f"/projects/{_pid()}/engine/canon", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "canon_context", "GET", f"/projects/{_pid()}/engine/canon/context", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "canon_create", "POST", f"/projects/{_pid()}/engine/canon", AuthLevel.PROJECT_WRITE,
                 json_body={"category": "world", "rule": "r", "severity": "hard"}),
    EndpointSpec("engine", "canon_patch", "PATCH", f"/projects/{_pid()}/engine/canon/{{rule_id}}",
                 AuthLevel.PROJECT_WRITE, json_body={"rule": "patched"}, positive_status=(200, 404)),
    EndpointSpec("engine", "canon_delete", "DELETE", f"/projects/{_pid()}/engine/canon/{{rule_id}}",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 404)),
    EndpointSpec("engine", "canon_get", "GET", f"/projects/{_pid()}/engine/canon/{{rule_id}}", AuthLevel.PROJECT_READ,
                 positive_status=(200, 404)),
    EndpointSpec("engine", "canon_validate", "POST", f"/projects/{_pid()}/engine/canon/validate",
                 AuthLevel.PROJECT_WRITE, json_body={"content": "test", "unit_index": 1}),
    EndpointSpec("engine", "override_budget", "GET", f"/projects/{_pid()}/engine/override-budget/{{unit_index}}",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "pipelines_list", "GET", f"/projects/{_pid()}/engine/pipelines", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "pipelines_create", "POST", f"/projects/{_pid()}/engine/pipelines", AuthLevel.PROJECT_WRITE,
                 json_body={"name": "test"}, positive_status=(200, 400)),
    EndpointSpec("engine", "pipelines_get", "GET", f"/projects/{_pid()}/engine/pipelines/{{run_id}}",
                 AuthLevel.PROJECT_READ, positive_status=(200, 404)),
    EndpointSpec("engine", "pipelines_patch", "PATCH", f"/projects/{_pid()}/engine/pipelines/{{run_id}}",
                 AuthLevel.PROJECT_WRITE, json_body={"status": "paused"}, positive_status=(200, 404)),
    EndpointSpec("engine", "governor_decide", "POST", f"/projects/{_pid()}/engine/governor/decide",
                 AuthLevel.PROJECT_WRITE, json_body={"critic_report": {}}, positive_status=(200, 400)),
    EndpointSpec("engine", "critic_reports_list", "GET", f"/projects/{_pid()}/engine/critic-reports",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "critic_reports_create", "POST", f"/projects/{_pid()}/engine/critic-reports",
                 AuthLevel.PROJECT_WRITE, json_body={"report": {}, "unit_index": 1}),
    EndpointSpec("engine", "critic_latest", "GET", f"/projects/{_pid()}/engine/critic/latest", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "critic_run", "POST", f"/projects/{_pid()}/engine/critic/run", AuthLevel.PROJECT_WRITE,
                 json_body={"unit_index": 1}, positive_status=(200, 400, 502)),
    EndpointSpec("engine", "critic_llm", "POST", f"/projects/{_pid()}/engine/critic/llm", AuthLevel.PROJECT_WRITE,
                 json_body={"unit_index": 1}, positive_status=(200, 400, 502)),
    EndpointSpec("engine", "pipeline_run", "POST", f"/projects/{_pid()}/engine/pipeline/run", AuthLevel.PROJECT_WRITE,
                 json_body={"unit_index": 1}, positive_status=(200, 400, 502)),
    EndpointSpec("engine", "memory_sync", "POST", f"/projects/{_pid()}/engine/memory/sync", AuthLevel.PROJECT_WRITE,
                 json_body={"unit_index": 1, "content": "x", "verify_status": "pass"}),
    EndpointSpec("engine", "memory_facts_get", "GET", f"/projects/{_pid()}/engine/memory/facts", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "memory_facts_post", "POST", f"/projects/{_pid()}/engine/memory/facts",
                 AuthLevel.PROJECT_WRITE, json_body={"fact": "test", "category": "event", "unit_index": 1}),
    EndpointSpec("engine", "memory_summaries", "GET", f"/projects/{_pid()}/engine/memory/summaries",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "memory_summary_get", "GET", f"/projects/{_pid()}/engine/memory/summaries/{{unit_index}}",
                 AuthLevel.PROJECT_READ, positive_status=(200, 404)),
    EndpointSpec("engine", "memory_summary_put", "PUT", f"/projects/{_pid()}/engine/memory/summaries/{{unit_index}}",
                 AuthLevel.PROJECT_WRITE, json_body={"summary": "s"}, positive_status=(200,)),
    EndpointSpec("engine", "memory_context", "GET", f"/projects/{_pid()}/engine/memory/context/{{unit_index}}",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "analysis_get", "GET", f"/projects/{_pid()}/engine/analysis", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "analysis_post", "POST", f"/projects/{_pid()}/engine/analysis", AuthLevel.PROJECT_WRITE,
                 json_body={"unit_index": 1}),
    EndpointSpec("engine", "creator_context", "GET", f"/projects/{_pid()}/engine/creator-context/{{unit_index}}",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "self_review_extract", "POST", f"/projects/{_pid()}/engine/self-review/extract",
                 AuthLevel.PROJECT_WRITE, json_body={"output": "text"}),
    EndpointSpec("engine", "voice_dna_list", "GET", f"/projects/{_pid()}/engine/voice-dna", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "voice_dna_get", "GET", f"/projects/{_pid()}/engine/voice-dna/{{character_id}}",
                 AuthLevel.PROJECT_READ, positive_status=(200, 404)),
    EndpointSpec("engine", "voice_dna_put", "PUT", f"/projects/{_pid()}/engine/voice-dna/{{character_id}}",
                 AuthLevel.PROJECT_WRITE, json_body={"traits": []}, positive_status=(200, 404)),
    EndpointSpec("engine", "voice_dna_train", "POST", f"/projects/{_pid()}/engine/voice-dna/{{character_id}}/train",
                 AuthLevel.PROJECT_WRITE, json_body={"character_name": "主角"}, positive_status=(200, 400, 404)),
    EndpointSpec("engine", "bible_get", "GET", f"/projects/{_pid()}/engine/bible", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "bible_put", "PUT", f"/projects/{_pid()}/engine/bible", AuthLevel.PROJECT_WRITE,
                 json_body={"sections": []}),
    EndpointSpec("engine", "bible_sections_post", "POST", f"/projects/{_pid()}/engine/bible/sections",
                 AuthLevel.PROJECT_WRITE, json_body={"title": "设定", "content": "c"}),
    EndpointSpec("engine", "bible_sections_delete", "DELETE", f"/projects/{_pid()}/engine/bible/sections/{{section_id}}",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 404)),
    EndpointSpec("engine", "beats_get", "GET", f"/projects/{_pid()}/engine/beats", AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "beats_put", "PUT", f"/projects/{_pid()}/engine/beats/{{unit_index}}",
                 AuthLevel.PROJECT_WRITE, json_body={"beats": []}),
    EndpointSpec("engine", "beats_write_plan", "POST", f"/projects/{_pid()}/engine/beats/{{unit_index}}/write-plan",
                 AuthLevel.PROJECT_WRITE, positive_status=(200, 400)),
    EndpointSpec("engine", "character_graph", "GET", f"/projects/{_pid()}/engine/character-graph",
                 AuthLevel.PROJECT_READ),
    EndpointSpec("engine", "export", "POST", f"/projects/{_pid()}/engine/export", AuthLevel.PROJECT_WRITE,
                 json_body={"format": "md", "download": False}),

    # ── Screenplay (film) ──
    EndpointSpec("screenplay", "get", "GET", f"/projects/{_pid('screenplay_project_id')}/screenplay",
                 AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "patch", "PATCH", f"/projects/{_pid('screenplay_project_id')}/screenplay",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"title": "patched"}),
    EndpointSpec("screenplay", "stats", "GET", f"/projects/{_pid('screenplay_project_id')}/screenplay/stats",
                 AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "scenes_create", "POST", f"/projects/{_pid('screenplay_project_id')}/screenplay/scenes",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"location": "场景A"}),
    EndpointSpec("screenplay", "scenes_patch", "PATCH",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/scenes/{{scene_id}}",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"synopsis": "x"}, positive_status=(200, 404)),
    EndpointSpec("screenplay", "scenes_delete", "DELETE",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/scenes/{{scene_id}}",
                 AuthLevel.SCREENPLAY_WRITE, positive_status=(200, 404)),
    EndpointSpec("screenplay", "scenes_reorder", "POST",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/scenes/reorder",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"order": []}, positive_status=(200, 400)),
    EndpointSpec("screenplay", "storylines_get", "GET",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/storylines", AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "storylines_put", "PUT",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/storylines",
                 AuthLevel.SCREENPLAY_WRITE, json_body=[]),
    EndpointSpec("screenplay", "characters", "GET",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/characters", AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "foreshadows_get", "GET",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/foreshadows", AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "foreshadows_put", "PUT",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/foreshadows",
                 AuthLevel.SCREENPLAY_WRITE, json_body=[]),
    EndpointSpec("screenplay", "foreshadows_create", "POST",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/foreshadows",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"title": "伏笔"}),
    EndpointSpec("screenplay", "foreshadows_patch", "PATCH",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/foreshadows/{{foreshadow_id}}",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"title": "x"}, positive_status=(200, 404)),
    EndpointSpec("screenplay", "character_arcs", "GET",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/character-arcs", AuthLevel.SCREENPLAY),
    EndpointSpec("screenplay", "character_arc_patch", "PATCH",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/character-arcs/{{character_name}}",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"arc": "growth"}, positive_status=(200, 404)),
    EndpointSpec("screenplay", "export_fountain", "GET",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/export/fountain", AuthLevel.SCREENPLAY,
                 positive_status=(200, 400)),
    EndpointSpec("screenplay", "episodes_create", "POST",
                 f"/projects/{_pid('screenplay_project_id')}/screenplay/episodes",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"title": "第1集"}, positive_status=(200, 400)),
    EndpointSpec("screenplay", "rhythm", "GET",
                 f"/projects/{_pid('web_short_project_id')}/screenplay/rhythm", AuthLevel.SCREENPLAY,
                 positive_status=(200, 404)),
    EndpointSpec("screenplay", "platform_put", "PUT",
                 f"/projects/{_pid('web_short_project_id')}/screenplay/platform",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"platform": "douyin"}, positive_status=(200, 404)),
    EndpointSpec("screenplay", "shots_create", "POST",
                 f"/projects/{_pid('web_short_project_id')}/screenplay/shots",
                 AuthLevel.SCREENPLAY_WRITE, json_body={"title": "镜头1"}, positive_status=(200, 400, 404)),
    EndpointSpec("screenplay", "sections_put", "PUT",
                 f"/projects/{_pid('web_short_project_id')}/screenplay/sections",
                 AuthLevel.SCREENPLAY_WRITE, json_body=[], positive_status=(200, 404)),

    # ── Guestbook ──
    EndpointSpec("guestbook", "list", "GET", "/guestbook/", AuthLevel.AUTH, query={"page": 1, "limit": 10}),
    EndpointSpec("guestbook", "create", "POST", "/guestbook/", AuthLevel.AUTH,
                 positive_status=(201, 400), notes="multipart"),
    EndpointSpec("guestbook", "reply", "POST", "/guestbook/{post_id}/replies", AuthLevel.AUTH,
                 positive_status=(201, 400, 404), notes="multipart"),
    EndpointSpec("guestbook", "delete_post", "DELETE", "/guestbook/{post_id}", AuthLevel.ADMIN,
                 positive_status=(200, 400, 404)),
    EndpointSpec("guestbook", "delete_reply", "DELETE", "/guestbook/{post_id}/replies/{reply_id}", AuthLevel.ADMIN,
                 positive_status=(200, 400, 404)),
    EndpointSpec("guestbook", "media", "GET", "/guestbook/media/{filename}", AuthLevel.PUBLIC,
                 positive_status=(200, 404), skip_auth_negative=True),
]

ALL_ENDPOINTS = _ALL_ENDPOINTS_RAW


def resolve_path(path: str, ctx: dict[str, str]) -> str:
    out = path
    for key, val in ctx.items():
        out = out.replace("{" + key + "}", val)
    return out


def resolve_body(body: Any, ctx: dict[str, str]) -> Any:
    if body is None:
        return None
    if isinstance(body, dict):
        return {k: resolve_body(v, ctx) if isinstance(v, str) else v for k, v in body.items()}
    if isinstance(body, str):
        for key, val in ctx.items():
            body = body.replace("{" + key + "}", val)
        return body
    return body
